#! /bin/zsh

./gradlew build && mv build/libs/EndFightModFabric-1.7.10-1.1.1.jar "/Users/andrew/Library/Application Support/PolyMC/instances/end_fight_mod1.7/.minecraft/mods/EndFightModFabric-1.7.10-1.1.1.jar"
